from quickfind import QF
from quickunion import QU
from weightedquickunion import WQU
from weightedquickunionwithpathcompression import WQUPC
if __name__ == "__main__":
    qf = QF(10)
    qf.union(0,5)
    qf.union(5,6)
    qf.union(1,2)
    qf.union(2,7)
    qf.union(3,4)
    qf.union(4,8)
    qf.union(8,9)
    print(qf.id)
    qf.union(1,6)
    print(qf.id)
    qf.union(1,3)
    print(qf.id)
    print("*"*20)


    qu = QU(10)
    print(qu.id)
    qu.union(0,5)
    print(qu.id)
    qu.union(1,6)
    print(qu.id)
    qu.union(3,1)
    print(qu.id)
    qu.union(0,1)
    print(qu.id)

    wqu = WQU(10)
    wqu.union(0,1)
    wqu.union(2,1)
    wqu.union(3,4)
    wqu.union(4,5)
    wqu.union(6,7)
    wqu.union(8,7)
    wqu.union(9,7)
    print(wqu.id)
    wqu.union(2,4)
    print(wqu.id)
    wqu.union(0,4)
    print(wqu.id)
    wqu.union(0,9)
    print(wqu.id)
    wqu.union(0,9)
    print(wqu.id)
    wqu.union(0,8)
    print(wqu.id)
    wqu.union(0,7)
    print(wqu.id)
    wqu.union(0,6)
    print(wqu.id)
    wqu.union(5,9)
    print(wqu.id)

    print("*"*30)

    wqupc = WQUPC(10)
    wqupc.union(0,1)
    wqupc.union(2,1)
    wqupc.union(3,4)
    wqupc.union(4,5)
    wqupc.union(6,7)
    wqupc.union(8,7)
    wqupc.union(9,7)
    print(wqupc.id)
    wqupc.union(2,4)
    print(wqupc.id)
    wqupc.union(0,4)
    print(wqupc.id)
    wqupc.union(0,9)
    print(wqupc.id)
    wqupc.union(0,9)
    wqupc.union(0,8)
    wqupc.union(0,7)
    wqupc.union(0,6)
    wqupc.union(5,9)
    print(wqupc.id)
    print(wqu.id)
    
    