[package]
name = "dna_seq_rust"
version = "0.1.0"
authors = ["livexia <istillalive@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bio for read fasta
bio = "0.33.0"
image = "0.23.14"