[package]
name = "insertion_sort"
version = "0.1.0"
authors = ["livexia <istillalive@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"